/**
 * @file static_init_runtime.h
 * @brief Runtime support for target-side degraded static initializers.
 */
#pragma once

#include "n00b.h"

/**
 * @brief C-ABI callback used by degraded static-initializer tables.
 *
 * A callback is generated by ncc for one static initializer that cannot be
 * baked for the requested target. It runs after n00b_init_simple(), may use
 * ordinary runtime allocation, stores the initializer value in the program's
 * writable data, and returns 0 on success.
 *
 * @return 0 on success; a nonzero process-style status on failure. The table
 *         walker stops at the first nonzero result and the generated CRT entry
 *         exits with that status.
 */
typedef int (*n00b_static_init_fn_t)(void);

/**
 * @brief Run a caller-supplied range of degraded static-initializer callbacks.
 *
 * @param start First table entry to inspect. Null requests a no-op.
 * @param end One-past-the-last table entry to inspect. Null requests a no-op.
 *
 * @pre  @p start and @p end either delimit a valid contiguous table of
 *       n00b_static_init_fn_t entries, or either pointer is null to request a
 *       no-op. Entries may be null and are skipped.
 * @post returns 0 when all non-null entries return 0; otherwise returns the
 *       first nonzero callback status and stops before later entries.
 *
 * @return 0 for an empty, null, or fully successful range; otherwise the first
 *         nonzero callback return value.
 */
int n00b_run_degraded_static_init_range(const n00b_static_init_fn_t *start,
                                        const n00b_static_init_fn_t *end);

/**
 * @brief Run link-time registered degraded static initializers for this process.
 *
 * @pre  called after n00b_init_simple has initialized the runtime and before
 *       user main observes static-init state. The generated ncc CRT entry is
 *       the intended caller. Initializer callbacks must be ordinary C runtime
 *       functions and return 0 on success.
 * @post returns 0 when no degrade table exists or all entries succeed; returns
 *       the first nonzero callback status so the generated entry can fail
 *       closed with n00b_exit(status).
 *
 * @return 0 when no platform degrade section is linked or all callbacks
 *         succeed; otherwise the first nonzero callback return value.
 */
int n00b_run_degraded_static_inits(void);
