// annot_walk.c - Post-parse DFS annotation walk.
//
// Walks the parse tree depth-first. For each non-terminal node, checks
// the grammar for annotations. Scope annotations push on entry and
// pop on exit (bracket the child recursion). Declaration annotations
// extract names and register them in the symbol table.

#include "slay/annot_walk.h"
#include "slay/annotation.h"
#include "internal/slay/grammar_internal.h"
#include "core/alloc.h"
#include "core/dict_untyped.h"
#include "strings/string_ops.h"

#include <stdio.h>


// ============================================================================
// Child reference resolution
// ============================================================================

// Find a child tree node by name, recursing through $$group nodes.
//
// Group nodes are generated by BNF quantifiers (?, *, +). Both PWZ and
// earley trees have group_top → content NTs directly (earley's group_item
// wrappers are normalized away by earley_forest.c:normalize_groups()).
static n00b_parse_tree_t *
find_child_by_name(n00b_grammar_t *g, n00b_parse_tree_t *parent, n00b_string_t name)
{
    size_t nc = n00b_tree_num_children(parent);

    for (size_t i = 0; i < nc; i++) {
        n00b_parse_tree_t *child = n00b_tree_child(parent, i);

        if (n00b_tree_is_leaf(child)) {
            continue;
        }

        n00b_nt_node_t *cpn = &n00b_tree_node_value(child);

        if (cpn->group_top) {
            // Group wrapper — recurse into it to find the target NT.
            n00b_parse_tree_t *found = find_child_by_name(g, child, name);

            if (found) {
                return found;
            }

            continue;
        }

        // Non-group node — check if its NT name matches.
        if (cpn->id >= 0) {
            n00b_nonterm_t *nt = n00b_get_nonterm(g, cpn->id);

            if (nt && n00b_unicode_str_eq(nt->name, name)) {
                return child;
            }
        }
    }

    return NULL;
}

// Resolve a child_ref to a tree node.
static n00b_parse_tree_t *
resolve_child_ref(n00b_grammar_t *g, n00b_parse_tree_t *parent,
                  n00b_child_ref_t ref)
{
    switch (ref.kind) {
    case N00B_ROLE_BY_INDEX:
        if (ref.index < 0) {
            return NULL;
        }

        if ((size_t)ref.index >= n00b_tree_num_children(parent)) {
            return NULL;
        }

        return n00b_tree_child(parent, ref.index);

    case N00B_ROLE_BY_NAME:
        return find_child_by_name(g, parent, ref.name);
    }

    return NULL;
}

// ============================================================================
// Name extraction
// ============================================================================

// Extract the text of the leftmost terminal (identifier) in a subtree.
// Recurses through internal nodes and $$group nodes to find the first token.
//
// Returns a non-empty string on success, or n00b_string_empty() on failure.
// Callers must check .u8_bytes > 0 (not just .data) since n00b_string_empty()
// has .data pointing to "" (not NULL).
static n00b_string_t
extract_first_identifier(n00b_parse_tree_t *node)
{
    if (!node) {
        return n00b_string_empty();
    }

    if (n00b_tree_is_leaf(node)) {
        n00b_token_info_t *tok = n00b_tree_leaf_value(node);

        if (tok && n00b_option_is_set(tok->value)) {
            n00b_string_t val = n00b_option_get(tok->value);

            if (val.u8_bytes > 0) {
                return val;
            }
        }

        return n00b_string_empty();
    }

    // Recurse into children to find the first token.
    size_t nc = n00b_tree_num_children(node);

    for (size_t i = 0; i < nc; i++) {
        n00b_string_t s = extract_first_identifier(n00b_tree_child(node, i));

        if (s.u8_bytes > 0) {
            return s;
        }
    }

    return n00b_string_empty();
}

// ============================================================================
// DFS walk
// ============================================================================

static void
walk_node(n00b_annot_walk_ctx_t *ctx, n00b_parse_tree_t *node)
{
    if (!node) {
        return;
    }

    // Terminals (leaves) have no annotations.
    if (n00b_tree_is_leaf(node)) {
        return;
    }

    n00b_nt_node_t *pn = &n00b_tree_node_value(node);

    // Empty-string nodes and negative IDs have no annotations.
    if (pn->id == N00B_EMPTY_STRING || pn->id < 0) {
        return;
    }

    // Group wrapper nodes are internal BNF artifacts (from ?, *, +
    // quantifiers). They carry no annotations — just recurse through them.
    if (pn->group_top) {
        size_t nc = n00b_tree_num_children(node);

        for (size_t i = 0; i < nc; i++) {
            walk_node(ctx, n00b_tree_child(node, i));
        }

        return;
    }

    n00b_nonterm_t *nt = n00b_get_nonterm(ctx->grammar, pn->id);

    if (!nt) {
        // Unknown NT — just recurse.
        size_t nc = n00b_tree_num_children(node);

        for (size_t i = 0; i < nc; i++) {
            walk_node(ctx, n00b_tree_child(node, i));
        }

        return;
    }

    // --- Pre-order: process annotations before recursing ---

    n00b_parse_rule_t *rule = n00b_get_node_rule(ctx->grammar, pn);

    n00b_list_t(n00b_annotation_t *) *annot_list = NULL;

    if (rule && rule->annotations.data) {
        annot_list = &rule->annotations;
    }

    // Track whether we opened a scope so we can pop it after children.
    bool          opened_scope = false;
    n00b_string_t scope_ns     = n00b_string_empty();

    size_t annot_count = annot_list ? n00b_list_len(*annot_list) : 0;

    // Track last registered symbol for @type stamping.
    n00b_sym_entry_t *last_sym = NULL;

    // ---- Loop 1: symbol registration (DECLARES, TYPE_DECL, ADT, FIELD, METHOD, TYPE) ----

    for (size_t ai = 0; ai < annot_count; ai++) {
        n00b_annotation_t *a = n00b_list_get(*annot_list, ai);

        switch (a->kind) {
        case N00B_ANNOT_DECLARES: {
            n00b_parse_tree_t *name_node
                = resolve_child_ref(ctx->grammar, node, a->name_ref);
            n00b_string_t sym_name
                = name_node ? extract_first_identifier(name_node)
                            : n00b_string_empty();

            if (sym_name.u8_bytes > 0) {
                last_sym = n00b_symtab_add(ctx->symtab,
                                            n00b_string_empty(),
                                            sym_name,
                                            N00B_SYM_VARIABLE,
                                            node);
            }

            break;
        }

        case N00B_ANNOT_TYPE_DECL: {
            n00b_parse_tree_t *name_node
                = resolve_child_ref(ctx->grammar, node, a->name_ref);
            n00b_string_t sym_name
                = name_node ? extract_first_identifier(name_node)
                            : n00b_string_empty();

            if (sym_name.u8_bytes > 0) {
                last_sym = n00b_symtab_add(ctx->symtab,
                                            n00b_string_empty(),
                                            sym_name,
                                            N00B_SYM_TYPEDEF,
                                            node);
            }

            break;
        }

        case N00B_ANNOT_ADT: {
            // Register the tag name in the "tag" namespace (parent scope).
            n00b_parse_tree_t *name_node
                = resolve_child_ref(ctx->grammar, node, a->name_ref);
            n00b_string_t tag_name
                = name_node ? extract_first_identifier(name_node)
                            : n00b_string_empty();

            if (tag_name.u8_bytes > 0) {
                n00b_sym_entry_t *sym = n00b_symtab_add(
                    ctx->symtab,
                    *r"tag",
                    tag_name,
                    N00B_SYM_TAG,
                    node);

                // Refine adt_kind: "struct_or_union" → "struct" or "union"
                // by inspecting the keyword child.
                n00b_string_t kind = a->adt_kind;

                if (kind.u8_bytes > 0
                    && n00b_unicode_str_eq(kind, *r"struct_or_union")) {
                    n00b_parse_tree_t *kw_node = find_child_by_name(
                        ctx->grammar, node, *r"_kw_kw_struct_or_union");

                    if (kw_node) {
                        n00b_string_t kw = extract_first_identifier(kw_node);

                        if (kw.u8_bytes > 0) {
                            kind = kw;
                        }
                    }
                }

                sym->adt_kind = kind;
                last_sym      = sym;
            }

            break;
        }

        case N00B_ANNOT_FIELD: {
            n00b_parse_tree_t *name_node
                = resolve_child_ref(ctx->grammar, node, a->name_ref);
            n00b_string_t field_name
                = name_node ? extract_first_identifier(name_node)
                            : n00b_string_empty();

            if (field_name.u8_bytes > 0) {
                n00b_parse_tree_t *type_node
                    = resolve_child_ref(ctx->grammar, node, a->type_ref);

                n00b_sym_entry_t *sym = n00b_symtab_add(
                    ctx->symtab,
                    n00b_string_empty(),
                    field_name,
                    N00B_SYM_VARIABLE,
                    node);

                sym->is_field  = true;
                sym->type_node = type_node;
                last_sym       = sym;
            }

            break;
        }

        case N00B_ANNOT_METHOD: {
            n00b_parse_tree_t *name_node
                = resolve_child_ref(ctx->grammar, node, a->name_ref);
            n00b_string_t method_name
                = name_node ? extract_first_identifier(name_node)
                            : n00b_string_empty();

            if (method_name.u8_bytes > 0) {
                n00b_parse_tree_t *type_node
                    = resolve_child_ref(ctx->grammar, node, a->type_ref);

                n00b_sym_entry_t *sym = n00b_symtab_add(
                    ctx->symtab,
                    n00b_string_empty(),
                    method_name,
                    N00B_SYM_FUNCTION,
                    node);

                sym->is_method = true;
                sym->type_node = type_node;
                last_sym       = sym;
            }

            break;
        }

        case N00B_ANNOT_TYPE: {
            // Stamp the last-registered symbol with type info.
            if (last_sym) {
                n00b_parse_tree_t *type_node
                    = resolve_child_ref(ctx->grammar, node, a->name_ref);

                if (type_node) {
                    last_sym->type_node = type_node;
                }
            }

            break;
        }

        default:
            break;
        }
    }

    // ---- Loop 2: scope + CF labels (SCOPE_OPEN, ADT scope push, BRANCH, LOOP, etc.) ----

    for (size_t ai = 0; ai < annot_count; ai++) {
        n00b_annotation_t *a = n00b_list_get(*annot_list, ai);

        switch (a->kind) {
        case N00B_ANNOT_SCOPE_OPEN: {
            scope_ns = a->scope_tag;

            n00b_string_t scope_name = n00b_string_empty();

            if (a->name_ref.kind == N00B_ROLE_BY_INDEX
                    ? a->name_ref.index >= 0
                    : a->name_ref.name.data != NULL) {
                n00b_parse_tree_t *name_node
                    = resolve_child_ref(ctx->grammar, node, a->name_ref);

                if (name_node) {
                    scope_name = extract_first_identifier(name_node);
                }
            }

            n00b_symtab_push_scope(ctx->symtab, scope_ns, scope_name);
            opened_scope = true;
            break;
        }

        case N00B_ANNOT_ADT: {
            // Push a new scope for the ADT body.
            n00b_string_t ns = a->scope_tag.data ? a->scope_tag
                                                  : n00b_string_empty();
            scope_ns = ns;

            n00b_parse_tree_t *name_node
                = resolve_child_ref(ctx->grammar, node, a->name_ref);
            n00b_string_t scope_name
                = name_node ? extract_first_identifier(name_node)
                            : n00b_string_empty();

            // Generate a unique scope name for anonymous ADTs.
            if (scope_name.u8_bytes == 0) {
                char buf[32];
                snprintf(buf, sizeof(buf), "anon_%d", ctx->anon_counter++);
                scope_name = n00b_string_from_cstr(buf);
            }

            n00b_symtab_push_scope(ctx->symtab, ns, scope_name);

            // Tag the scope with the refined ADT kind.
            n00b_scope_t *scope = n00b_symtab_current_scope(ctx->symtab, ns);

            if (scope) {
                n00b_string_t kind = a->adt_kind;

                if (kind.u8_bytes > 0
                    && n00b_unicode_str_eq(kind, *r"struct_or_union")) {
                    n00b_parse_tree_t *kw_node = find_child_by_name(
                        ctx->grammar, node, *r"_kw_kw_struct_or_union");

                    if (kw_node) {
                        n00b_string_t kw = extract_first_identifier(kw_node);

                        if (kw.u8_bytes > 0) {
                            kind = kw;
                        }
                    }
                }

                scope->adt_kind = kind;
            }

            opened_scope = true;
            break;
        }

        case N00B_ANNOT_BRANCH: {
            n00b_cf_label_t *label = n00b_alloc(n00b_cf_label_t);
            label->kind      = N00B_CF_BRANCH;
            label->self      = node;
            label->cond      = resolve_child_ref(ctx->grammar, node, a->name_ref);
            label->then_body = resolve_child_ref(ctx->grammar, node, a->type_ref);
            label->else_body = resolve_child_ref(ctx->grammar, node, a->value_ref);
            _n00b_dict_untyped_put(ctx->cf_labels, node, label);
            break;
        }

        case N00B_ANNOT_LOOP: {
            n00b_cf_label_t *label = n00b_alloc(n00b_cf_label_t);
            label->kind      = N00B_CF_LOOP;
            label->self      = node;
            label->cond      = resolve_child_ref(ctx->grammar, node, a->name_ref);
            label->then_body = resolve_child_ref(ctx->grammar, node, a->type_ref);
            _n00b_dict_untyped_put(ctx->cf_labels, node, label);
            break;
        }

        case N00B_ANNOT_SWITCH: {
            n00b_cf_label_t *label = n00b_alloc(n00b_cf_label_t);
            label->kind      = N00B_CF_SWITCH;
            label->self      = node;
            label->cond      = resolve_child_ref(ctx->grammar, node, a->name_ref);
            label->then_body = resolve_child_ref(ctx->grammar, node, a->type_ref);
            _n00b_dict_untyped_put(ctx->cf_labels, node, label);
            break;
        }

        case N00B_ANNOT_JUMP: {
            n00b_cf_label_t *label = n00b_alloc(n00b_cf_label_t);
            label->kind      = N00B_CF_JUMP;
            label->self      = node;
            label->jump_kind = a->scope_tag;

            if (!label->jump_kind.data) {
                label->jump_kind = extract_first_identifier(node);
            }

            _n00b_dict_untyped_put(ctx->cf_labels, node, label);
            break;
        }

        case N00B_ANNOT_CAPTURE: {
            n00b_cf_label_t *label = n00b_alloc(n00b_cf_label_t);
            label->kind           = N00B_CF_CAPTURE;
            label->self           = node;
            label->tag            = a->scope_tag;
            label->capture_by_tag = a->capture_by_tag;
            _n00b_dict_untyped_put(ctx->cf_labels, node, label);
            break;
        }

        case N00B_ANNOT_ASSIGNS: {
            n00b_cf_label_t *label = n00b_alloc(n00b_cf_label_t);
            label->kind      = N00B_CF_ASSIGNS;
            label->self      = node;
            label->cond      = resolve_child_ref(ctx->grammar, node, a->name_ref);
            label->then_body = resolve_child_ref(ctx->grammar, node, a->value_ref);
            _n00b_dict_untyped_put(ctx->cf_labels, node, label);
            break;
        }

        default:
            break;
        }
    }

    // --- Recurse into children ---

    size_t nc = n00b_tree_num_children(node);

    for (size_t i = 0; i < nc; i++) {
        walk_node(ctx, n00b_tree_child(node, i));
    }

    // --- Post-order: pop scope if we pushed one ---

    if (opened_scope) {
        n00b_symtab_pop_scope(ctx->symtab, scope_ns);
    }
}

// ============================================================================
// Public API — full result (symtab + control flow labels)
// ============================================================================

n00b_annot_result_t *
n00b_annot_walk_tree_full(n00b_grammar_t *g, n00b_parse_tree_t *tree)
{
    if (!g || !tree) {
        return NULL;
    }

    n00b_dict_untyped_t *labels = n00b_alloc(n00b_dict_untyped_t);
    n00b_dict_untyped_init(labels, .skip_obj_hash = true);

    n00b_annot_walk_ctx_t ctx = {
        .symtab    = n00b_symtab_new(),
        .grammar   = g,
        .cf_labels = labels,
    };

    walk_node(&ctx, tree);

    n00b_annot_result_t *result = n00b_alloc(n00b_annot_result_t);
    result->symtab    = ctx.symtab;
    result->cf_labels = ctx.cf_labels;

    return result;
}

n00b_annot_result_t *
n00b_annot_walk_full(n00b_parse_result_t *result)
{
    if (!result || !n00b_parse_result_ok(result)) {
        return NULL;
    }

    n00b_grammar_t    *g    = n00b_parse_result_grammar(result);
    n00b_parse_tree_t *tree = n00b_parse_result_tree(result);

    return n00b_annot_walk_tree_full(g, tree);
}

// ============================================================================
// Public API — symtab only (convenience wrappers)
// ============================================================================

n00b_symtab_t *
n00b_annot_walk_tree(n00b_grammar_t *g, n00b_parse_tree_t *tree)
{
    n00b_annot_result_t *r = n00b_annot_walk_tree_full(g, tree);

    return r ? r->symtab : NULL;
}

n00b_symtab_t *
n00b_annot_walk(n00b_parse_result_t *result)
{
    n00b_annot_result_t *r = n00b_annot_walk_full(result);

    return r ? r->symtab : NULL;
}
