// Auto-generated by `cargo run --bin build_byte_freq -- <corpus_path>`
// in resharp-c.  Higher value = more common = worse prefilter candidate.
//
// Phase 10 port: relocated from resharp-c/include/simd/byte_freq.h.  The
// table is renamed to the `n00b_simd_*` prefix for the externally-visible
// symbol; callers in the regex engine use `n00b_simd_BYTE_FREQ`.
#pragma once

#include <stdint.h>

extern const uint16_t n00b_simd_BYTE_FREQ[256];
