#!/usr/bin/env python3
"""
WP-005 — embed the audit-rule-file metagrammar as a C string
constant in a generated header. Reads the input BNF file and
writes a header defining N00B_AUDIT_RULE_FILE_METAGRAMMAR as a
(const char *) string literal carrying the file contents
verbatim (with `\\`, `"`, and newlines escaped per C-string
rules).

Usage: embed_metagrammar.py <input.bnf> <output.h>
"""
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_metagrammar.py <input.bnf> <output.h>",
              file=sys.stderr)
        return 1
    in_path, out_path = sys.argv[1], sys.argv[2]
    with open(in_path, "rb") as fh:
        src = fh.read().decode("utf-8")
    lines = src.split("\n")
    n = len(lines)
    out_lines = [
        "#pragma once",
        "",
        "/* Auto-generated by scripts/embed_metagrammar.py from",
        " * grammars/audit-rule-file.bnf — do not edit. */",
        "",
        "#define N00B_AUDIT_RULE_FILE_METAGRAMMAR \\",
    ]
    for i, line in enumerate(lines):
        esc = line.replace("\\", "\\\\").replace("\"", "\\\"")
        suffix = "\\n" if i + 1 < n else ""
        cont = " \\" if i + 1 < n else ""
        out_lines.append("    \"" + esc + suffix + "\"" + cont)
    out_lines.append("")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out_lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
