#!/usr/bin/env python3
"""Embed a UTF-8 text file as C string data in a generated header.

Emits a static array (never a multi-line `#define`) so large resources do
not become one preprocessor line, which native Windows/ncc builds reject.
Input is read with universal newlines so CRLF checkouts embed as LF, and
the generated comment stays ASCII for non-UTF-8 source charsets.

Usage: embed_metagrammar.py <input> <output.h> [symbol]
"""
import os
import sys


def c_escape(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == "\"":
            out.append("\\\"")
        elif ch == "\t":
            out.append("\\t")
        elif 0x20 <= ord(ch) <= 0x7e:
            out.append(ch)
        else:
            out.extend(f"\\{b:03o}" for b in ch.encode("utf-8"))
    return "".join(out)


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print("usage: embed_metagrammar.py <input> <output.h> [symbol]",
              file=sys.stderr)
        return 1
    in_path, out_path = sys.argv[1], sys.argv[2]
    symbol = (sys.argv[3] if len(sys.argv) == 4
              else "N00B_AUDIT_RULE_FILE_METAGRAMMAR")
    with open(in_path, "r", encoding="utf-8", newline=None) as fh:
        src = fh.read()
    lines = src.split("\n")
    n = len(lines)
    out_lines = [
        "#pragma once",
        "",
        "/* Auto-generated by scripts/embed_metagrammar.py from",
        f" * {os.path.basename(in_path)} - do not edit. */",
        "",
        f"static const char {symbol}[] =",
    ]
    for i, line in enumerate(lines):
        esc = c_escape(line)
        suffix = "\\n" if i + 1 < n else ""
        out_lines.append("    \"" + esc + suffix + "\"")
    out_lines.append("    \"\";")
    out_lines.append("")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out_lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
